Add desktop access informations
ThePorgs/Exegol-docs pull request #46
Opened 2024-04-16 16:02 UTC by QU35T-code

Adding access information to the exegol desktop

2024-05-10 21:39 UTC, Dramelac requested changes

2024-05-10 21:39 UTC, Dramelac commented on source/assets/desktop.png
Can you remove the header bar from your browser ? The desktop can be reach via VNC too.

2024-05-12 17:09 UTC, QU35T-code commented on source/assets/desktop.png
Done @Dramelac

2024-05-12 17:11 UTC, Dramelac approved these changes

2024-05-12 17:11 UTC, merged