Update faq.rst
ThePorgs/Exegol-docs pull request #57
Opened 2024-09-26 06:00 UTC by Pri3st

Added a workaround for WSL 2 consuming high amounts of RAM, leading to reduced performance of the host machine.

2024-10-10 22:42 UTC, ShutdownRepo requested changes
Thank you, one change and we'll be good to go, thank you @Pri3st !!

2024-10-10 22:42 UTC, ShutdownRepo commented on source/getting-started/faq.rst
> +============================================
We need equal number of `=` to len(title)

2024-10-20 18:30 UTC, Pri3st commented
Hey @ShutdownRepo , I will also need to add another workaround to deal with WSL2 getting too much disk space. I have found a solution with the `diskpart` tool which can significantly free up space because WSL2 seems to be increasingly claiming disk space that cannot be controlled through the `.wslconfig` file. In my case, after an Exegol image update, WSL2 claimed an additional 60GB  of disk space (the previous image version was deleted) so I had to troubleshoot a bit to resolve this.

I think it will be a good addition to this PR. I will add the workaround and let you know.

2024-10-29 16:25 UTC, Pri3st commented
@ShutdownRepo the FAQ section is now complete, you can review it at your convenience.

2024-12-11 10:51 UTC, ShutdownRepo approved these changes

2024-12-11 10:51 UTC, ShutdownRepo commented
Looks good to me, thank you for your contribution to the Exegol project @Pri3st !!

2024-12-11 10:51 UTC, merged