Change bashrc to bash_aliases source for installation
ThePorgs/Exegol-docs pull request #71
Opened 2024-11-23 15:31 UTC by Sh3llch0k

Corrected the source command after adding exegol alias in .bash_aliases (.bashrc doesn't include .bash_aliases by default on some distros like Arch Linux).

2024-11-23 15:52 UTC, Dramelac requested changes
Using `.bash_aliases` is intended in order to follow best practice.
If your `.bashrc` doesn't include `.bash_aliases` if the file exist you should add this config instead.

Moreover, changing the source file to `.bash_aliases` in the doc will not fix any issue because it'll only work for your one current session but will not be auto-loaded next time.

2024-11-24 09:43 UTC, Sh3llch0k commented
> Using `.bash_aliases` is intended in order to follow best practice. If your `.bashrc` doesn't include `.bash_aliases` if the file exist you should add this config instead.
> 
> Moreover, changing the source file to `.bash_aliases` in the doc will not fix any issue because it'll only work for your one current session but will not be auto-loaded next time.

Noted, I will add a tip section instead of modifying the source command then.

2024-12-16 07:16 UTC, ShutdownRepo commented
lgtm, @Dramelac agreed ?

2024-12-16 08:02 UTC, Dramelac approved these changes

2024-12-16 13:54 UTC, merged